JWT
uktrade/lite-oauth2-poc pull request #4
Opened 2020-08-28 08:40 UTC by richtier

2020-09-01 09:26 UTC, kerin requested changes
A couple of questions around the python library used for OIDC, and the handling of the OIDC client ID and secret.

2020-09-01 09:26 UTC, kerin commented on lite-api/lite_api/settings.py
> +            'secret': env.str('DJANGO_ALLAUTH_AUTH0_CLIENT_SECRET'),
Can we verify that client ID and secret are required here when using RS256 as signing algorithm? The public key for signature validation can be obtained from the JWK key set provided at `tenant.auth0.com/.well-known/jwks.json`, so unless the client secret and ID are used for purposes other than validating the JWT they shouldn't be required - see:

https://auth0.com/blog/navigating-rs256-and-jwks/
https://auth0.com/docs/tokens/json-web-tokens/validate-json-web-tokens

2020-09-01 09:26 UTC, kerin commented on lite-api/lite_api/settings.py
> +    'allauth.socialaccount.providers.auth0',
I'm slightly suspicious of using a specific Auth0 library, as here we're just using Auth0 as an OIDC-compliant stand-in for staff-sso/great-sso - could you try using a  vendor-agnostic generic OIDC library instead, such as https://github.com/mozilla/mozilla-django-oidc ?

2020-09-01 09:26 UTC, kerin commented on lite-internal-frontend/auth/views.py
> +class Auth0OAuth2Adapter(views.Auth0OAuth2Adapter):
Is this using allauth Auth0 oauth views to handle OIDC logins, or is this actually using an oauth flow?

2020-09-01 13:30 UTC, richtier commented on lite-api/lite_api/settings.py
> +    'allauth.socialaccount.providers.auth0',
will switch to the mozilla one :+1: 

for reference tho `allauth` has a collection of hundreds of oauth2 identity providers (facebook, twitter, linkedin, aut0, etc). used it as it was quick to set up

2020-09-01 13:32 UTC, richtier commented on lite-internal-frontend/auth/views.py
> +class Auth0OAuth2Adapter(views.Auth0OAuth2Adapter):
oauth flow is being used. 

by default allauth throws away the jwt and just does another reqest to auth0 like a barbarian. here were grabbing the JWT before it's thrown away.

will no longer need this once we move to the mozilla lib

2020-10-28 10:26 UTC, kerin approved these changes

2020-10-28 15:34 UTC, merged